export const ANIMATION_DURATION = {
  IMAGE_BRIGHTNESS: 0.3,
  IMAGE_SCALE: 2,
  TEXT_SCROLL: 3,
  TEXT_FADE_IN: 0.1,
  TEXT_FADE_IN_DELAY: 0.1,
  CONTAINER_HEIGHT: 0.3,
};

export const CONFIG = {
  SMALL_VIEWPORT_MAX_WIDTH: 860,
  MIN_VIEWPORT_HEIGHT: 600,
  MAX_VIEWPORT_WIDTH: 1920,
  SCALE_MULTIPLIER: 1.2,
  MIN_SCALE: 2,
  SCROLL_MULTIPLIER: 2,
};
